/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud.clientes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import crud.clientes.clases.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sebas
 */
public class VentanaFacturacion extends javax.swing.JFrame {

    ClienteManager cmanager = new ClienteManager();
    VendedorManager vmanager = new VendedorManager();
    FacturaManager fmanager = new FacturaManager();
    ProductoManager pmanager = new ProductoManager();
    SucursalManager smanager = new SucursalManager();
    DetalleFacturaManager dmanager = new DetalleFacturaManager();
    String cedulaVendedor;
    String codigoSucursal;
    String[] columnNames = {"Código", "Descripción", "Unidad Medida", "Cantidad", "Valor Unitario", "Subtotal","Paga IVA"};
    DefaultTableModel model = new DefaultTableModel();
    double subtotalf=0;
    double total=0;
    int i=-1;
    double comision=0;
    /**
     * Creates new form VentanaFacturacion
     */
    public VentanaFacturacion(String cedula_ruc_vendedor, String codigosucursal, double comision1) throws SQLException {
        initComponents();
        int numeroFactura = fmanager.obtenerNumeroFacturaDisponible();
        String facturaNumero = String.valueOf(numeroFactura);
        numero_factura_txt.setText(facturaNumero);
        cedulaVendedor = cedula_ruc_vendedor;
        vendedor_factura_txt.setText(cedulaVendedor);
        codigoSucursal = codigosucursal;
        sucursal_factura_txt.setText(codigoSucursal);
        setFechaActual();
        iva_txt.setText("15%");
        subtotal_txt.setText(String.valueOf(subtotalf));
        total_txt.setText(String.valueOf(total));
        fillComboBox();
        comision=comision1;
        //this.tamanoMaximo();
        
    }
    private void fillComboBox() throws SQLException {
        // Crear lista de strings
        List<String> itemList = new ArrayList();
        itemList = fmanager.obtenerFormasPago();
        pago_txt.removeAllItems();
        // Agregar elementos al JComboBox
        for (String item : itemList) {
            pago_txt.addItem(item);
        }
    }
    public void tamanoMaximo() {        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        this.setSize(screenSize.width, screenSize.height);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);    
    }
     private void setFechaActual() {
        // Obtiene la fecha actual
        LocalDate fechaActual = LocalDate.now();
        
        // Formatea la fecha actual en el formato 'dd/MM/yyyy'
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/M/yyyy");
        String fechaFormateada = fechaActual.format(formatter);
        fecha_factura_txt.setText(fechaFormateada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numero_factura_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fecha_factura_txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subtotal_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        iva_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total_txt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        sucursal_factura_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        cliente_factura_txt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cedula_cliente_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre_cliente_txt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        vendedor_factura_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        barras_txt = new javax.swing.JTextField();
        descripcion_txt = new javax.swing.JTextField();
        prd_codigo_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_producto = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cantidad_txt = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        pago_txt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(new java.awt.Color(216, 239, 211));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TODO PRODUCTOS S.A.");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Unidad Medida", "Cantidad", "Valor Unitario", "Subtotal", "Paga IVA"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarFila(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("Factura No:");

        numero_factura_txt.setEditable(false);

        jLabel5.setText("Fecha:");

        fecha_factura_txt.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(85, 173, 155));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 10, 1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Subtotal");
        jPanel2.add(jLabel8);

        subtotal_txt.setEditable(false);
        jPanel2.add(subtotal_txt);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("IVA");
        jPanel2.add(jLabel9);

        iva_txt.setEditable(false);
        jPanel2.add(iva_txt);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total");
        jPanel2.add(jLabel10);

        total_txt.setEditable(false);
        jPanel2.add(total_txt);

        jButton6.setText("Eliminar producto del detalle");
        jButton6.setActionCommand("Eliminar Producto del detalle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("Sucursal Emisora:");

        sucursal_factura_txt.setEditable(false);

        jSeparator1.setBackground(new java.awt.Color(85, 173, 155));
        jSeparator1.setForeground(new java.awt.Color(85, 173, 155));

        jLabel19.setText("Cliente:");

        cliente_factura_txt.setEditable(false);

        jPanel3.setBackground(new java.awt.Color(149, 210, 179));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre"
            }
        ));
        tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_cliente);

        jLabel3.setText("Cédula");

        jLabel4.setText("Nombre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula_cliente_txt)
                            .addComponent(nombre_cliente_txt)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedula_cliente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(nombre_cliente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel22.setText("Vendedor");

        vendedor_factura_txt.setEditable(false);

        jButton3.setText("Generar Factura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Seleccione el cliente");

        jLabel24.setText("Seleccionar Producto");

        jButton7.setText("Nuevo Cliente");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Historial Facturas");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(149, 210, 179));

        jLabel14.setText("Codigo Producto:");

        jLabel15.setText("Descripción:");

        jLabel17.setText("Código de barra:");

        jButton5.setText("Buscar producto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tabla_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Stock"
            }
        ));
        tabla_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarproducto(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_producto);

        jLabel16.setText("Cantidad");

        cantidad_txt.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton4.setText("Añadir Producto al detalle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prd_codigo_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(descripcion_txt)
                            .addComponent(barras_txt)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad_txt))
                    .addComponent(jButton4))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(prd_codigo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(barras_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cantidad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(51, 51, 51))
        );

        pago_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Seleccione la forma de pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(596, 596, 596)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cliente_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel18)
                                .addGap(32, 32, 32)
                                .addComponent(sucursal_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(vendedor_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jButton6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(pago_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel12)
                        .addGap(521, 521, 521)
                        .addComponent(jLabel24)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(fecha_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(sucursal_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(cliente_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(vendedor_factura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel24))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(pago_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cedula = cedula_cliente_txt.getText();
        String nombre = nombre_cliente_txt.getText().toUpperCase();
        String query = "SELECT * FROM cliente WHERE 1=1";

        if (!cedula.isEmpty()) {
            query += " AND cli_cedula_ruc LIKE '" + cedula + "%'";
        }

        if (!nombre.isEmpty()) {
            query += " AND cli_nombre LIKE '" + nombre + "%'";
        }
        ResultSet rs;
        try {
            rs = cmanager.buscarConQuery(query);
            String[] columnNames = {"Cédula/Ruc", "Nombre"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            while (rs.next()) {
                String cedulaRuc1 = rs.getString("cli_cedula_ruc");
                String nombre3 = rs.getString("cli_nombre");

                model.addRow(new Object[]{cedulaRuc1, nombre3});
            }
            tabla_cliente.setModel(model);
            tabla_cliente.setRowHeight(50);

        } catch (SQLException ex) {
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //SE DEBE VERIFICAR QUE EXISTA LA CANTIDAD DEL PRODUCTO INDICA EN ESA SUCURSAL. SI NO, NO PERMITE AÑADIR
        int cantidadSolicitada;
        cantidadSolicitada = (int) cantidad_txt.getValue();
        String codigop = prd_codigo_txt.getText();
        String sucCodigo = sucursal_factura_txt.getText();
        
        if (!codigop.isEmpty()) {
            if (cantidadSolicitada > 0) {
                int stockproducto;
                try {
                    stockproducto = pmanager.obtenerCantidadEnStock(codigop, sucCodigo);
                    if (stockproducto >= cantidadSolicitada) {
                        ResultSet rs;
                        try {
                            rs = pmanager.obtenerProductoPorCodigo(codigop);
                            model.setColumnIdentifiers(columnNames);
                            while (rs.next()) {
                                String codigo = rs.getString("PRD_CODIGO");
                                String descripcion = rs.getString("PRD_DESCRIPCION");
                                // Para este ejemplo, se usarán valores fijos o calculados para las columnas no disponibles en la base de datos
                                String unidadMedida = "Unidad"; // Este valor puede ser calculado o derivado
                                int cantidad = 1; // Por defecto 1, esto podría ser un parámetro o venir de otro input
                                double valorUnitario = rs.getDouble("PRD_PRECIO");
                                double subtotal = cantidadSolicitada * valorUnitario;
                                subtotalf += subtotal;
                                String pagaiva = rs.getString(7);
                                if (pagaiva.equals("S")) {
                                    total += (subtotal + (subtotal * (0.15)));
                                } else {
                                    total += subtotal;
                                }
                                model.addRow(new Object[]{codigo, descripcion, unidadMedida, cantidadSolicitada, valorUnitario, subtotal, pagaiva});
                            }

                            tabla.setModel(model);
                            tabla.setRowHeight(50);

                        } catch (SQLException ex) {
                            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad solicitada supera al numéro en stock");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                subtotal_txt.setText(String.valueOf(subtotalf));
                total_txt.setText(String.valueOf(total));
            }
            else
                JOptionPane.showMessageDialog(null, "La cantidad solicitada debe ser mayor a 0");

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (i != -1) {
            try {
                if (i >= 0) {
                    String aux = tabla.getValueAt(i, 5).toString();
                    double subtotalaux = Double.parseDouble(aux);
                    String pagaIvaAux = tabla.getValueAt(i, 6).toString();
                    if (pagaIvaAux.equals("S")) {
                        total -= (subtotalaux + (subtotalaux * 0.15));
                        subtotalf -= subtotalaux;
                    } else {
                        total -= subtotalaux;
                        subtotalf -= subtotalaux;
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Fila no seleccionada");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
            }
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            model.removeRow(i);
            tabla.setModel(model);
            subtotal_txt.setText(String.valueOf(subtotalf));
            total_txt.setText(String.valueOf(total));
        } else
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto para eliminarlo del detalle");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //fmanager.insertarFactura(Integer.parseInt(numero_factura_txt.getText()), codigoSucursal, "T-003", cliente_factura_txt, cedulaVendedor, fecha_factura_txt.getText(), total, "V");
        double totalAmount = Double.parseDouble(total_txt.getText());
        fmanager.insertarFactura(
                Integer.parseInt(numero_factura_txt.getText()), // Convierte el texto a entero
                codigoSucursal, // Ya está en el formato correcto
                "T-003", // Cadena de texto directamente
                cliente_factura_txt.getText(), // Obtiene el texto del JTextField
                cedulaVendedor, // Ya está en el formato correcto
                fecha_factura_txt.getText(), // Convierte el texto a Date, asumiendo formato YYYY-MM-DD
                totalAmount, // Convierte el texto a double
                "V" // Estado directamente como cadena de texto
        );
        int totalRows = tabla.getRowCount();
        for(int j=0; j< totalRows; j++)
        {
            String cod_producto=(tabla.getValueAt(j, 0).toString()); 
            String cantidad_producto=(tabla.getValueAt(j, 3).toString());
            int cantidad_detfac= Integer.parseInt(cantidad_producto);
            String aux=(tabla.getValueAt(j, 5).toString());
            double subtotal_detfac = Double.parseDouble(aux);

            // Convertimos a BigDecimal para redondear a 2 decimales
            BigDecimal bd = new BigDecimal(Double.toString(subtotal_detfac));
            bd = bd.setScale(2, RoundingMode.HALF_UP); // Redondea a 2 decimales

            // Convertimos de nuevo a double
            subtotal_detfac = bd.doubleValue();
            try {
                dmanager.insertarDetalleFactura(Integer.parseInt(numero_factura_txt.getText()), cod_producto, cantidad_detfac, subtotal_detfac);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        double aux=Double.parseDouble(subtotal_txt.getText());
        double valcomision=aux*(comision/100);
        String aux2=numero_factura_txt.getText();
        int nfac = Integer.parseInt(aux2);
        int ncom;
        try {
            ncom = vmanager.obtenerNumeroComisión();
            vmanager.insertarComision(String.valueOf(ncom), cedulaVendedor, fecha_factura_txt.getText(), fecha_factura_txt.getText(), fecha_factura_txt.getText(), valcomision, nfac);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            VentanaFacturacion nuevo = new VentanaFacturacion(cedulaVendedor,codigoSucursal,comision);
            this.setVisible(false);
            nuevo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        VentanaAcciones c;
        try {
            
            c = new VentanaAcciones(this);
            c.setTitle("Ventana Cliente");
            c.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String codigo = prd_codigo_txt.getText().toUpperCase();
        String descripcion = descripcion_txt.getText().toUpperCase();
        String cbarras = barras_txt.getText();
        String sucursal = sucursal_factura_txt.getText();
        String query = "SELECT "
                + "p.PRD_CODIGO, "
                + "p.PRD_DESCRIPCION, "
                + "pb.PRB_EXISTENCIA "
                + "FROM sucursal s "
                + "JOIN bodega b ON s.SUC_CODIGO = b.SUC_CODIGO "
                + "JOIN producto_bodega pb ON b.BOD_CODIGO = pb.BOD_CODIGO "
                + "JOIN producto p ON pb.PRD_CODIGO = p.PRD_CODIGO "
                + "WHERE s.SUC_CODIGO = '" + sucursal + "'";
        if (!codigo.isEmpty()) {
            query += " AND p.PRD_CODIGO LIKE '%" + codigo + "%'";
        }

        if (!descripcion.isEmpty()) {
            query += " AND p.PRD_DESCRIPCION LIKE '%" + descripcion + "%'";
        }

        if (!cbarras.isEmpty()) {
            query += " AND p.PRD_CODIGO_BARRA LIKE '%" + cbarras + "%'";
        }

        ResultSet rs;
        try {
            rs = fmanager.buscarConQuery(query);
            String[] columnNames = {"Codigo", "Descripcion", "Stock"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            try {
                while (rs.next()) {
                    String codigoProducto = rs.getString("PRD_CODIGO");
                    String descripcionProducto = rs.getString("PRD_DESCRIPCION");
                    String existencia = rs.getString("PRB_EXISTENCIA");  // Ajusta según tus columnas reales
                    model.addRow(new Object[]{codigoProducto, descripcionProducto, existencia});
                }
                tabla_producto.setModel(model);
                tabla_producto.setRowHeight(50);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        // TODO add your handling code here:
        try{
            int fila = tabla_cliente.getSelectedRow();
            if (fila >= 0) {
                cliente_factura_txt.setText(tabla_cliente.getValueAt(fila, 0).toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Fila no seleccionada");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
        }
    }//GEN-LAST:event_click

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        VentanaFacturas f;
        try {
            f = new VentanaFacturas();
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void seleccionarproducto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarproducto
        // TODO add your handling code here:
        try{
            int fila = tabla_producto.getSelectedRow();
            if (fila >= 0) {
                prd_codigo_txt.setText(tabla_producto.getValueAt(fila, 0).toString()); 
                descripcion_txt.setText(tabla_producto.getValueAt(fila, 1).toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Fila no seleccionada");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
        }
    }//GEN-LAST:event_seleccionarproducto

    private void seleccionarFila(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarFila
        // TODO add your handling code here:
        i = tabla.getSelectedRow();
    }//GEN-LAST:event_seleccionarFila

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barras_txt;
    private javax.swing.JSpinner cantidad_txt;
    private javax.swing.JTextField cedula_cliente_txt;
    private javax.swing.JTextField cliente_factura_txt;
    private javax.swing.JTextField descripcion_txt;
    private javax.swing.JTextField fecha_factura_txt;
    private javax.swing.JTextField iva_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre_cliente_txt;
    private javax.swing.JTextField numero_factura_txt;
    private javax.swing.JComboBox<String> pago_txt;
    private javax.swing.JTextField prd_codigo_txt;
    private javax.swing.JTextField subtotal_txt;
    private javax.swing.JTextField sucursal_factura_txt;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla_cliente;
    private javax.swing.JTable tabla_producto;
    private javax.swing.JTextField total_txt;
    private javax.swing.JTextField vendedor_factura_txt;
    // End of variables declaration//GEN-END:variables
}
