/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud.clientes;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import crud.clientes.clases.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sebas
 */
public class VentanaAcciones extends javax.swing.JFrame {    
    ClienteManager manager = new ClienteManager();
    
    /**
     * Creates new form VentanaAddCliente
     */
    VentanaFacturacion inicio;
    public VentanaAcciones() throws SQLException {
        initComponents();
        fillComboBox();
        
    }
    public VentanaAcciones(VentanaFacturacion inicio) throws SQLException {
        this.inicio = inicio;
        inicio.setVisible(false); 
        initComponents();
        fillComboBox();
    }

    private void fillComboBox() throws SQLException {
        // Crear lista de strings
        List<String> itemList = new ArrayList();
        itemList = manager.obtenerCodCiudades();

        // Agregar elementos al JComboBox
        for (String item : itemList) {
            ciudad_txt.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cedula_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        apellido_txt = new javax.swing.JTextField();
        correo_txt = new javax.swing.JTextField();
        ciudad_txt = new javax.swing.JComboBox<>();
        telefono_txt = new javax.swing.JTextField();
        direccion_txt = new javax.swing.JTextField();
        sector_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(216, 239, 211));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 173, 155));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Cédula:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Correo:");

        cedula_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarCedula(evt);
            }
        });
        cedula_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_txtActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Ciudad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Teléfono:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Sector:");

        nombre_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Limpiar(evt);
            }
        });
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });

        apellido_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarApellido(evt);
            }
        });

        correo_txt.setToolTipText("");
        correo_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarCorreo(evt);
            }
        });

        ciudad_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera" }));
        ciudad_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudad_txtActionPerformed(evt);
            }
        });

        telefono_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarTelefono(evt);
            }
        });

        direccion_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarDir(evt);
            }
        });

        sector_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarSector(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula/Ruc", "Código Ciudad", "Nombre", "Apellido", "Correo", "Teléfono", "Dirección", "Sector"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
                seleccionarCliente(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jButton1.setBackground(new java.awt.Color(85, 173, 155));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jButton1.setText("Ver todos los clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(85, 173, 155));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jButton2.setText("Buscar por parámetros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(85, 173, 155));
        jButton4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Actualizar Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(85, 173, 155));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Eliminar Cliente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(85, 173, 155));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Limpiar casillas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(85, 173, 155));
        jButton7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Crear Cliente");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(correo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellido_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ciudad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(138, 138, 138)
                .addComponent(jButton2)
                .addGap(255, 255, 255))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(727, 727, 727)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(sector_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4)
                .addGap(41, 41, 41)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedula_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(apellido_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ciudad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(correo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(direccion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(sector_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton6))
                        .addGap(172, 172, 172))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedula_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_txtActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_cedula_txtActionPerformed

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void Limpiar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Limpiar
        // TODO add your handling code here:
        nombre_txt.setText("");
    }//GEN-LAST:event_Limpiar

    private void LimpiarCedula(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarCedula
        // TODO add your handling code here:
        cedula_txt.setText("");
    }//GEN-LAST:event_LimpiarCedula

    private void LimpiarApellido(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarApellido
        // TODO add your handling code here:
        apellido_txt.setText("");
    }//GEN-LAST:event_LimpiarApellido

    private void LimpiarCorreo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarCorreo
        // TODO add your handling code here:
         correo_txt.setText("");
    }//GEN-LAST:event_LimpiarCorreo

    private void LimpiarTelefono(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarTelefono
        // TODO add your handling code here:
        telefono_txt.setText("");
    }//GEN-LAST:event_LimpiarTelefono

    private void LimpiarDir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarDir
        // TODO add your handling code here:
        direccion_txt.setText("");
    }//GEN-LAST:event_LimpiarDir

    private void LimpiarSector(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarSector
        // TODO add your handling code here:
        sector_txt.setText("");
    }//GEN-LAST:event_LimpiarSector

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        try {
            rs = manager.verTodosLosClientes();
            String[] columnNames = {"Cédula/Ruc", "Código Ciudad", "Nombre", "Apellido", "Correo", "Teléfono", "Dirección", "Sector"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            while (rs.next()) {
                String cedulaRuc = rs.getString("cli_cedula_ruc");
                String ciudad = rs.getString("ciu_codigo");
                String nombre = rs.getString("cli_nombre");
                String apellido = rs.getString("cli_apellido");
                String correo = rs.getString("cli_correo");
                String telefono = rs.getString("cli_telefono");
                String direccion = rs.getString("cli_direccion");
                String sector = rs.getString("cli_sector");

                model.addRow(new Object[]{cedulaRuc, ciudad, nombre, apellido,correo,telefono,direccion,sector});
            }
            tabla.setRowHeight(50);
            tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setSize(1236, 1118);
        String cedulaRuc = cedula_txt.getText();
        String ciudad = ciudad_txt.getSelectedItem().toString();         
        String nombre = nombre_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String apellido = apellido_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String correo = correo_txt.getText();
        String telefono = telefono_txt.getText();
        String direccion = direccion_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String sector = sector_txt.getText().toUpperCase(); // Convertir a mayúsculas

        String query = "SELECT * FROM cliente WHERE 1=1";
        System.out.println(ciudad);

        if (!cedulaRuc.isEmpty()) {
            query += " AND cli_cedula_ruc LIKE '" + cedulaRuc + "%'";
        }

        if (!ciudad.equals("Cualquiera")) {
            query += " AND ciu_codigo LIKE '%" + ciudad + "'";
        }

        if (!nombre.isEmpty()) {
            query += " AND cli_nombre LIKE '" + nombre + "%'";
        }

        if (!apellido.isEmpty()) {
            query += " AND cli_apellido LIKE '" + apellido + "%'";
        }

        if (!correo.isEmpty()) {
            query += " AND cli_correo LIKE '%" + correo + "%'";
        }

        if (!telefono.isEmpty()) {
            query += " AND cli_telefono LIKE '" + telefono + "%'";
        }

        if (!direccion.isEmpty()) {
            query += " AND cli_direccion LIKE '%" + direccion + "%'";
        }

        if (!sector.isEmpty()) {
            query += " AND cli_sector LIKE '%" + sector + "%'";
        }

        ResultSet rs;
        try {
            rs = manager.buscarConQuery(query);
            String[] columnNames = {"Cédula/Ruc", "Código Ciudad", "Nombre", "Apellido", "Correo", "Teléfono", "Dirección", "Sector"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);
            while (rs.next()) {
                String cedulaRuc1 = rs.getString("cli_cedula_ruc");
                String codigoCiudad2 = rs.getString("ciu_codigo");
                String nombre3 = rs.getString("cli_nombre");
                String apellido4 = rs.getString("cli_apellido");
                String correo5 = rs.getString("cli_correo");
                String telefono6 = rs.getString("cli_telefono");
                String direccion7 = rs.getString("cli_direccion");
                String sector8 = rs.getString("cli_sector");

                model.addRow(new Object[]{cedulaRuc1, codigoCiudad2, nombre3, apellido4, correo5, telefono6, direccion7, sector8});
            }
            tabla.setModel(model);
            tabla.setRowHeight(50);

        } catch (SQLException ex) {
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            manager.actualizarCliente(cedula_txt.getText(), ciudad_txt.getSelectedItem().toString(), nombre_txt.getText().toUpperCase(), apellido_txt.getText().toUpperCase(), correo_txt.getText(), telefono_txt.getText(), direccion_txt.getText().toUpperCase(), sector_txt.getText().toUpperCase());
            JOptionPane.showMessageDialog(null, "Cliente actualizado con éxito");
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void seleccionarCliente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarCliente
        // TODO add your handling code here:
        try{
            int fila = tabla.getSelectedRow();
            if (fila >= 0) {
                cedula_txt.setText(tabla.getValueAt(fila, 0).toString());
                ciudad_txt.setSelectedItem(tabla.getValueAt(fila, 1).toString());
                nombre_txt.setText(tabla.getValueAt(fila, 2).toString());
                apellido_txt.setText(tabla.getValueAt(fila, 3).toString());
                correo_txt.setText(tabla.getValueAt(fila, 4).toString());
                telefono_txt.setText(tabla.getValueAt(fila, 5).toString());
                direccion_txt.setText(tabla.getValueAt(fila, 6).toString());
                sector_txt.setText(tabla.getValueAt(fila, 7).toString());
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Fila no seleccionada");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
        }
    }//GEN-LAST:event_seleccionarCliente

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            manager.elminarCliente(cedula_txt.getText());
            JOptionPane.showMessageDialog(null, "Cliente eliminado con éxito");
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ciudad_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudad_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudad_txtActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cedula_txt.setText("");
        nombre_txt.setText("");
        apellido_txt.setText("");
        telefono_txt.setText("");
        correo_txt.setText("");
        direccion_txt.setText("");
        sector_txt.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String cedulaRuc = cedula_txt.getText();
        String ciudad = ciudad_txt.getSelectedItem().toString();
        String nombre = nombre_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String apellido = apellido_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String correo = correo_txt.getText();
        String telefono = telefono_txt.getText();
        String direccion = direccion_txt.getText().toUpperCase(); // Convertir a mayúsculas
        String sector = sector_txt.getText().toUpperCase(); // Convertir a mayúsculas
        boolean verificador = true;
        if(cedulaRuc.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar una cédula");
        }
        if(ciudad.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar una ciudad");
        }
        if(nombre.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar un nombre");
        }
        if(apellido.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar un apellido");
        }
        if(correo.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar un correo");
        }
        if(telefono.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar un teléfono");
        }
        if(direccion.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar una dirección");
        }
        if(sector.isEmpty())
        {
            verificador = false;
            JOptionPane.showMessageDialog(null,"Debe ingresar un sector");
        }
        try {
            if(verificador)
            {
                if(telefono.length()<9)
                {
                    verificador = false;
                    JOptionPane.showMessageDialog(null,"Debe ingresar un teléfono válido");
                }
                if (!(correo.contains("@") && correo.contains(".")))
                {
                    verificador = false;
                    JOptionPane.showMessageDialog(null,"Correo inválido");
                }
                if(verificador)
                {
                    manager.insertarCliente(cedulaRuc, ciudad, nombre, apellido, correo, telefono, direccion, sector);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_txt;
    private javax.swing.JTextField cedula_txt;
    private javax.swing.JComboBox<String> ciudad_txt;
    private javax.swing.JTextField correo_txt;
    private javax.swing.JTextField direccion_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTextField sector_txt;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables
}
