/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud.clientes;
import crud.clientes.clases.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author david
 */
public class VentanaFacturas extends javax.swing.JFrame {

    FacturaManager fmanager = new FacturaManager();
    ConexionOracle o = new ConexionOracle();
    int i=-1;
    /**
     * Creates new form VentanaFacturas
     */
    public VentanaFacturas() throws SQLException {
        initComponents();
        ResultSet rs;
        try {
            rs = fmanager.verTodasLasFacturas();

            String[] columnNames = {"FAC_NUMERO", "SUC_CODIGO", "TRN_CODIGO", "CLI_CEDULA_RUC", "VEN_CEDULA_RUC", "FAC_FECHA", "FAC_MONTO", "FAC_ESTADO"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            while (rs.next()) {
                int facNumero = rs.getInt("FAC_NUMERO");
                String sucCodigo = rs.getString("SUC_CODIGO");
                String trnCodigo = rs.getString("TRN_CODIGO");
                String cliCedulaRuc = rs.getString("CLI_CEDULA_RUC");
                String venCedulaRuc = rs.getString("VEN_CEDULA_RUC");
                Date facFecha = rs.getDate("FAC_FECHA");
                double facMonto = rs.getDouble("FAC_MONTO");
                String facEstado = rs.getString("FAC_ESTADO");

                model.addRow(new Object[]{facNumero, sucCodigo, trnCodigo, cliCedulaRuc, venCedulaRuc, facFecha, facMonto, facEstado});
            }

            tabla.setModel(model);
            tabla.setRowHeight(50);

        } catch (SQLException ex) {
            // Loguea cualquier excepción que ocurra durante la ejecución
            Logger.getLogger(VentanaAcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrd = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        numero_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(216, 239, 211));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FAC_NUMERO", "SUC_CODIGO", "TRN_CODIGO", "CLI_CEDULA_RUC", "VEN_CEDULA_RUC", "FAC_FECHA", "FAC_MONTO", "FAC_ESTADO"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarFactura(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL FACTURAS");

        jButton1.setText("Anular Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaPrd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FAC_NUMERO", "PRD_CODIGO", "DTF_CANTIDAD", "DTF_PRECIO"
            }
        ));
        jScrollPane2.setViewportView(tablaPrd);

        jLabel2.setText("Detalle de factura:");

        jButton2.setText("Buscar por número");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Factura Nro:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(119, 119, 119))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(numero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(numero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarFactura(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarFactura
        // TODO add your handling code here:
        i = tabla.getSelectedRow();
        try{
            int rowSelected = tabla.getSelectedRow();
            if (rowSelected >= 0) {
                String fac_numero = (tabla.getValueAt(rowSelected, 0).toString());
                int aux = Integer.parseInt(fac_numero);
                ResultSet rs;
                String query = "SELECT * FROM detalle_factura WHERE fac_numero ="+ aux;
                rs = o.executeQuery(query);
                String[] columnNames = {"FAC_NUMERO", "PRD_CODIGO","DTF_CANTIDAD","DTF_PRECIO"};
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(columnNames);
                while (rs.next()) {
                    int nfac= rs.getInt("fac_numero");
                    String codigoPrd = rs.getString("PRD_CODIGO");
                    int cantidadtf= rs.getInt("DTF_CANTIDAD");
                    double preciodtf=rs.getDouble("DTF_PRECIO");

                    model.addRow(new Object[]{nfac, codigoPrd,cantidadtf,preciodtf});
                }
                tablaPrd.setModel(model);
                tablaPrd.setRowHeight(50);
            } else {
                JOptionPane.showMessageDialog(null, "Fila no seleccionada");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
        }
    }//GEN-LAST:event_seleccionarFactura

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (i != -1) {
            try {
                if (i >= 0) {
                    int numero_fac = Integer.parseInt(tabla.getValueAt(i, 0).toString());
                    //String query = "UPDATE factura SET fac_estado = '" + "A" + "' WHERE fac_numero=" + numero_fac + ")";
                    String query = "UPDATE factura SET fac_estado = '" + "A" + "' WHERE fac_numero = " + numero_fac;
                    o.executeQuery(query);
                    JOptionPane.showMessageDialog(null, "Factura anulada");
                } else {
                    JOptionPane.showMessageDialog(null, "Fila no seleccionada");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error de seleccion, error: " + e.toString());
            }
        } else
            JOptionPane.showMessageDialog(null, "Debe seleccionar una factura para anularla");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM factura WHERE 1=1 ";
        String auxn = numero_txt.getText();
        if(auxn.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un número");
        }
        else
        {
            int auxN = Integer.parseInt(auxn);
            query += "AND fac_numero = " +auxN;
        }
        try {
            ResultSet rs;
            rs=fmanager.buscarConQuery(query);
            String[] columnNames = {"FAC_NUMERO", "SUC_CODIGO", "TRN_CODIGO", "CLI_CEDULA_RUC", "VEN_CEDULA_RUC", "FAC_FECHA", "FAC_MONTO", "FAC_ESTADO"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            while (rs.next()) {
                int facNumero = rs.getInt("FAC_NUMERO");
                String sucCodigo = rs.getString("SUC_CODIGO");
                String trnCodigo = rs.getString("TRN_CODIGO");
                String cliCedulaRuc = rs.getString("CLI_CEDULA_RUC");
                String venCedulaRuc = rs.getString("VEN_CEDULA_RUC");
                Date facFecha = rs.getDate("FAC_FECHA");
                double facMonto = rs.getDouble("FAC_MONTO");
                String facEstado = rs.getString("FAC_ESTADO");

                model.addRow(new Object[]{facNumero, sucCodigo, trnCodigo, cliCedulaRuc, venCedulaRuc, facFecha, facMonto, facEstado});
            }

            tabla.setModel(model);
            tabla.setRowHeight(50);
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numero_txt;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaPrd;
    // End of variables declaration//GEN-END:variables
}
